-- CURDATE() - DATA ATUAL NO FORMATO AMERICANO
SELECT CURDATE() AS 'Data Atual';

-- CURTIME() - RETORNA A HORA ATUAL
SELECT CURTIME() AS 'Hora Atual';

-- DATE_ADD(data, intervalo) - RETORNA UMA DATA ADICIONANDO UM INTERVALO DESEJADO
SELECT DATE_ADD(CURDATE(), INTERVAL 3 DAY) AS 'Data de Vencimento';

-- DATE_SUB (data, subtrai um intervalo) - RETORNA UMA DATA SUBTRAINDO UM INTERVALO DESEJADO
SELECT DATE_SUB(CURDATE(), INTERVAL 10 DAY) AS 'Data de matrícula';

-- DATEDIFF (expressão1, expressão2) - RETORNA O VALOR DA DIFERENÇA ENTRE EXPRESSÃO 1 E EXPRESSÃO2, PODENDO AMBOS SER UMA DATA OU DATA E HORÁRIO
SELECT DATEDIFF(CURDATE(), DATE_SUB(CURDATE(), INTERVAL 10 DAY)) AS 'Dia em Atrasos';

-- DATEFORMAT(data, formato) - RETORNA A DATA ATUAL FORMATADA
SELECT DATE_FORMAT(CURDATE(), '%d\%m\%Y') AS 'Data Formatada';

-- DAYNAME() - RETORNA O DIA DA SEMANA
SELECT DAYNAME(CURDATE()) AS 'Dia da Semana';

-- DAYOFMONTH() - RETORNA O DIA DO MÊS
SELECT DAYOFMONTH(CURDATE()) AS 'Dia do Mês';

-- DAYOFWEEK() - RETORNA O DIA DA SEMANA
SELECT DAYOFWEEK(CURDATE()) AS 'Dia da Semana';

-- DAYOFYEAR() - RETORNA O DIA DO ANO
SELECT DAYOFYEAR(CURDATE()) AS 'Dia do Ano';

-- FROMDAYS() - RETORNA A TRANSFORMANDO A NUMERAÇÃO INFORMADA PARA UMA DATA REFERENTE A ESSA NUMERAÇÃoptimize
SELECT FROM_DAYS(780500) AS 'Data';

-- NOW - RETORNA A DATA E A HORA ATUAL
SELECT NOW() AS 'Data e Hora Atual';

-- USANDO O NOW E DATE_FORMAT
SELECT DATE_FORMAT(NOW(), '%d\%m\%Y   %h:%m:%s') AS 'Data/Hora Atual';

-- SEC_TO_TIME - TRANSFORMA O VALOR DIGITADO EM HORAS
SELECT SEC_TO_TIME(24894) AS 'Tempo';

-- TIME_TO_SEC() - TRANSFORMA O VALOR DE HORAS EM SEGUNDOS
SELECT TIME_TO_SEC('54:05:25') AS 'Em Segundos';